
# Replace ###APPLICATION_NAME### with the application name you registered in the
# AppEngine Administration Console: https://appengine.google.com/
#
application: nickxbsapp
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: template.application

libraries:
- name: jinja2
  version: latest
